### ISSUE TITLE
Website problems with Behaviours and Technologies

### ISSUE THREAD

**Issue by ghost** [coar-repositories/ngr#3]
I've noticed two new problems on the website:

The lists of behaviors and technologies on the respective pages contain an href with an absolute URL using the http scheme.  Most links on the site use relative URLs with path only, so the scheme is relative to the current page.

The individual behaviour and technology pages are all missing their lists of related technologies and behaviours.

**Comment by paulwalk** [comment]
@wallberg-umd many thanks for reporting these issues - I have fixed them now!

**Comment by ghost** [comment]
You are welcome and thank you for this excellent resource.
